version: "3"

services:
  app:
    build: .
    environment:
      MONGO_HOST:  "mongodb://db:27017"
      MONGO_DATABASE: "test"
      EXPRESS_PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    depends_on:
      - db
  
  db:
    image: mongo
